<!doctype html>
<html lang="en">
  <head>
    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
      
  <div class="container py-3 mb-5">
    <a href="meeting_view.php" class="btn btn-primary mb-3">Go back</a>
    <div class='card mb-5'>
        <div class="card-header">
            Edit data
        </div>
            <form action='' class='row g-3 d-flex flex-column align-items-center px-5 py-3'  method='POST' autocomplete='off'>
                <input type="hidden" name="id" value="">
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>First Name</label>
                    <input placeholder='Hernando Hugo' type='text' class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Last Name</label>
                    <input placeholder='Perez Pedroza' type='text' class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Email</label>
                    <input placeholder='Example@email.com' type='text'  class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Phone Number</label>
                    <input placeholder='310 567 47 34' type='text'  class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Topic</label>
                    <input placeholder='Consultoria' type='text'  class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Description</label>
                    <input placeholder='Escribe algun texto' type='text'  class='form-control' required value="">
                </div>
                <div class="col-md-4 w-100">
                    <label for="label" class='form-label'>Date</label>
                    <input type='datetime-local' class='form-control' required value="">
                </div>
                <div class="col-md-12 ">
                    
                    <button class='btn btn-primary'>Save</button>
                </div>

            </form>
        </div>
    </div>


    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>