<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>
      
    <div class="container">
      <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">

          <?php foreach($get_meeting as $mrow){?>
          <div class="card">
            <div class="color rounded-3 w-100 bg-success h-auto"><span class="text-success">color div</span></div>
            <h2 class="text-center pt-2">Assigned meeting</h2>
            <div class="card-body">
              <h5 class="card-title"><?php echo $mrow['first_name'].' ' . $meeting['last_name'] ?></h5>
              <div class="text-cont d-flex flex-column">
                <span>- Email</span>
                <span>- Phone</span>
                <span>- Date</span>
              </div>

              <div class="icons d-flex justify-content-end gap-5 pe-3">
                <a class="link-success fs-5" href="#"><i class="fa-solid fa-pen-to-square"></i></a>
                <a class="link-danger fs-5" href="#"><i class="fa-solid fa-trash"></i></a>
              </div>

            </div>
          </div>
          <?php }?>
        </div>
      </div>
    </div>

    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>